### ISSUE TITLE
implement step intersections

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#117]
See https://www.mapbox.com/api-documentation/#routestep-object

https://github.com/hiposfer/kamal/blob/master/src/hiposfer/kamal/directions.clj#L85

**Comment by mehdisadeghi** [comment]
@carocad is this about adding a new API, right?

**Comment by carocad** [comment]
@mehdisadeghi no. Currently the datastructure that we return on the `directions` endpoint still lacks some pieces. the `steps` intersections is one of those.

This ticket is only about fixing that
