### ISSUE TITLE
consider compressing stop.times entities into frequency based model

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#126]
Most of the time spend routing a person with GTFS feeds is wasted searching the right trip/src/dst combination among thousands of entries (saarland has 189000 lines).

Even with a our current indexes it still takes around `1 milliseconds` to find the right entry. If we want to have query times of less than 100 milliseconds we cannot waste that much time per stop.

The current algorithm to solve that is frequency-based model: 
- http://ad-publications.informatik.uni-freiburg.de/GIS_frequencysearch_BS_2014

It basically compresses a route into a sequence of tuples of the form `[8:00, 15min, 41]` where the last element is the frequency. This a reduction from possibly hundreds of entries down to single one !!

**Comment by carocad** [comment]
the GTFS spec already contains a similar feature. It could be integrated directly into o2g :)

related issue: https://github.com/hiposfer/osmtogtfs/issues/84

**Comment by mehdisadeghi** [comment]
@carocad I'm working on that.

**Comment by carocad** [comment]
closing in favour of #224
