### ISSUE TITLE
direction api: make departure parameter optional

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/kamal#131]

**Comment by carocad** [comment]
@mehdisadeghi I dont think this is a very good idea. 

If an app with current LocalTime 08:32 forgets to send that parameter and the server is located at Zone + 2 then the default value created by the server would be 10:32 which is not what the user requested. The user wanted the departure at `his/her` localtime not at the localtime of the server.

**Comment by mehdisadeghi** [comment]
@carocad it totally makes sense. At least I learned some more Clojure doing this :)
