### ISSUE TITLE
consider accepting a pre-processed DataScript file

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#135]
Currently we parse both OSM and GTFS files on start. This however can take a lot of time and memory given the size of those files.

A better approach (for production) would be to have a processed file with the result of that transformation readily available for initialization.

Datascript supports serializing and deserializing itself into a string thus, it would be fairly simple to implement. 

We should check if this actually brings any performance gains :)

**Comment by mehdisadeghi** [comment]
@carocad this falls in the category of caching I think.

**Comment by carocad** [comment]
@mehdisadeghi definitely

This is a low prio for now as well.

I think that in the future it could be relevant for production servers since a 50 seconds boot is quite a lot. If we add more cities then the server start time would be even bigger which is not very good for spawing new containers.

**Comment by carocad** [comment]
I played around today with this and it would definitely speed up things for us. Using the Datascript reader the `network` building times goes from `65 seconds` to `10 seconds` in my machine.

However, since we are using Java objects, which dont have a default serializer in Clojure, we get some weird objects in the output which would have to be handled specially.

Here is the code that I used for it

```
;; code for writing a Datascript instance to a file
(with-open [w (clojure.java.io/writer "resources/datascript.edn")]
  (binding [*out* w]
    (pr @(first @(:networks (:router system))))))

;; -------------------------------
;; code for reading an EDN file into a Datascript instance
(with-open [r (PushbackReader. (clojure.java.io/reader "resources/datascript.edn"))]
  (binding [*read-eval* false]
    (edn/read {:readers (merge data/data-readers
                               {'hiposfer.kamal.network.core.Location hiposfer.kamal.network.core/map->Location
                                'object identity})} ;; HACK - we need to handle Java Objects properly
              r)))
```

**Comment by carocad** [comment]
> Do we have this problem only on loading/de-serializing the cached edn file?

we have it on serialization and deserialization. Clojure uses EDN format which is very similar to JSON. However Java Objects dont have a native representation so they end up in something like `Object [java.time.LocalDateTime] "08:27"` which the reader cannot deserialize (that is by the way the same thing that you see on a REPL if you try to print a Java object).

So we would have to provide a way to serialize and deserialize the Java Objects. More info here: https://github.com/clojure-cookbook/clojure-cookbook/blob/master/04_local-io/4-17_unknown-reader-literals.asciidoc

**Comment by carocad** [comment]
ok it seems that this is not so complicated after all

I managed to get it working on this branch: https://github.com/hiposfer/kamal/blob/edn-data/src/hiposfer/kamal/data.clj

It is still quite hacky but it works. I will polish it once I am back from holidays (2 weeks from now :) )

This reduces the read time from 90 seconds to 14 seconds on my machine (this results are different from before because now I am using Frankfurt data and we are streaming the zip file, not loading it from disk, which of course takes longer)
