### ISSUE TITLE
Find the right graph for the given coordinates

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/kamal#16]
Since we don't have the graph data for the whole planet earth, we need to compute the right graph for the given coordinates (sent from the client) before computing the route from the start to the destination. We also need to compute the graph boundary and make sure the coordinates are inside the given graph.

**Comment by carocad** [comment]
I think this can be done pretty easily so I will let you do it ;)

The way I would do it is:
- create an atom to store the current state of the system. Something like `(def networks [{:graph bla-bla :bbox [lat lon lat2 lon2]}]` would work for the time being. (So an array of network representations)
- once you receive a query you should loop through the graphs and see if the coordinates are inside the `:bbox` (this is from GeoJson, you can check it online)
-  If you got a hit then use the graph to compute the shortest
- otherweise return an error

on restrospective it might not be as simple as I expected ... but not that hard either :)
definitely a good excersise :+1:

**Comment by mehdisadeghi** [comment]
I had missed this one. I'll do it :)

**Comment by carocad** [comment]
@mehdisadeghi I think that with the latest nearest neighbour search addition, this should be straightforward.

However, we dont have multiple graphs per server so far so I am closing this. Feel free to re-open it if you think it is still relevant
