### ISSUE TITLE
determine where is most of the routing time spend

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#180]
In my machine, a call to `directions/` takes around `800 ms`. That is quite slow.

We are using the slowest algorithm though, however I think we can do much better. See #174 

We should find out where is most of the time being spend and if possible try to reduce it. note: currently I use VisualVM for those profiling tasks

**Comment by carocad** [comment]
<img width="1392" alt="screen shot 2018-07-08 at 14 53 00" src="https://user-images.githubusercontent.com/10408729/42419956-ad385576-82be-11e8-8702-378577776bdf.png">

I got this by calling `direction` a 1000 times while sampling the time spend with VisualVm. From there it is clear that most of the time is spent trying to find a trip to get into.

**Comment by mehdisadeghi** [comment]
Having a flame graph for the code would be nice, I have not heard of one for clojure yet however.

**Comment by carocad** [comment]
@mehdisadeghi Clojure generally relies on Java tooling. 

VisualVM (the tool that I use) is actually for Java 😅 but it is the free version .... I think the commercial alternatives might have that but I havent checked since it is not a prio for me

**Comment by carocad** [comment]
another data insignt from our network data:

```
(sort-by val (frequencies (map (comp namespace :a) @(first @(:networks (:router hiposfer.kamal.dev/system))))))
=>
(["area" 4]
 ["service" 8]
 ["agency" 112]
 ["route" 1277]
 ["stop" 11355]
 ["trip" 70848]
 ["way" 150529]
 ["node" 171357]
 ["stop_times" 1551420])
```

the stop times data is by far the largest in a network; at least in the frankfurt network.

Maybe we should try to compress this data a bit? no idea how to do that in the time being without any fancy algorithm

**Comment by carocad** [comment]
another data insignt related to #125 

There is in fact a big duplication of data for ways. Most of them share the same name which indicate that we might be able to simplify the network without lossing much precision on the map.

```clojure
(count
  ;(distinct
    (map :v
      (filter #(= :way/name (:a %))
              @(first @(:networks (:router hiposfer.kamal.dev/system))))))
```

For frankfurt this outputs:
- 3507 -> distinct way names
- 12866 -> total way count

Although I dont think anymore that creating a custom entity would be best. Now I think that we could reuse the `relation` definition from OSM and just use negative ids (since those are forbidden in osm) to make clear that those are custom made relations.

**Comment by carocad** [comment]
we can close this since we already know where is most of the time spent
