### ISSUE TITLE
consider replacing directions response code by http code

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#197]
Currently we send an HTTP ok even if we couldnt find an route.

This leads to the client having to extra check if the response actually contains a route before proceeding.

I think this should be done through an HTTP code instead of through the payload of the response (we inherited this from mapbox api ...)

@mehdisadeghi any opinion on this?

**Comment by mehdisadeghi** [comment]
Wouldn't it be ambiguous if a direction service returns for example an HTTP 404 error upon a routing request? Does it mean the service is offline or no route was found?

**Comment by carocad** [comment]
@mehdisadeghi see the PR #198 we dont return a 404 as (I agree with you) it would be ambiguous whether the resource is not available or no route was found.

In that PR we return a 412 - precondition failed. Basically saying:
- we couldnt find any coordinate matches inside that area (or)
- we couldnt find any route inside that area

See it here: https://github.com/hiposfer/kamal/pull/198/files#diff-a145d73b84641c03bc334deb98393a82R87

I think this makes it quite explicit. If we have a success then we return a route, otherwise we just return an appropiate error.
