### ISSUE TITLE
consider cleaning the git history of big files

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#229]
Through the development of kamal I have added and removed several zip/gz/edn/bz2 files to allow the integration tests to use them.

However since the preprocessing step is still unstable, those "big" files ended up changing quite often.

Right now this repo is around 100 MB, which in my opinions is quite big.

I think we should remove those files from the git history to loose some weight :)

more info: 
- https://confluence.atlassian.com/bitbucket/reduce-repository-size-321848262.html
- https://rtyley.github.io/bfg-repo-cleaner/

@mehdisadeghi any opinions on this? I guess `osmtogtfs` could eventually have the same problem

**Comment by carocad** [comment]
ALTERNATIVE:
stop putting those file inside the git repo and instead download them before the tests start

**Comment by mehdisadeghi** [comment]
I have done this once to get rid of some large files. I think the following will do (from [git docs](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)):

> This occurs fairly commonly. Someone accidentally commits a huge binary file with a thoughtless git add ., and you want to remove it everywhere. Perhaps you accidentally committed a file that contained a password, and you want to make your project open source. filter-branch is the tool you probably want to use to scrub your entire history. To remove a file named passwords.txt from your entire history, you can use the --tree-filter option to filter-branch:

    $ git filter-branch --tree-filter 'rm -f passwords.txt' HEAD
    Rewrite 6b9b3cf04e7c5686a9cb838c3f36a8cb6a0fc2bd (21/21)
    Ref 'refs/heads/master' was rewritten

**Comment by mehdisadeghi** [comment]
> stop putting those file inside the git repo

I agree with this. We have to add files that we are interested in their diffs such as source files, others are just clutter.
