### ISSUE TITLE
We have to test the code on Windows too

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/kamal#49]
Let's add appveyor to have free Windows tests!

**Comment by carocad** [comment]
Can we not get this with Travis?

Conversely with docker hub? From what I had understand the point of docker is precisely to isolate the executing program from the execution environment so if it rubs on docker we are good to go, right ? :)

**Comment by mehdisadeghi** [comment]
AFAIK Travis only provides Linux systems. Moreover, it is easy to setup :)

IMHO, no matter which deployment technology one uses (Docker or anything else) code should run on different operating systems. Docker and JRE will call OS routines at the end of the day and since each OS is different it is good to test on different platforms. Let's take threading as an example, different operating systems have different priorities, code that break on one might work on another one ...

**Comment by carocad** [comment]
@mehdisadeghi this is a quite old issue. Since I have not seen any activity neither from you nor from someone else on this I would close it.

It might become relevant later on, but it doesnt seem like that for the time being
