### ISSUE TITLE
script: parse Public transport relations from OSM to GTFS format

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#56]
We need to extract public transport information out of somewhere. Since there are no good GTFS files we could simply get those from OSM files

A general description of the related tags are here:
http://wiki.openstreetmap.org/wiki/Buses

this tool shows that it is definitely possible
https://öpnvkarte.de/#8.6889;50.095;15

http://wiki.openstreetmap.org/wiki/Public_transport

http://wiki.openstreetmap.org/wiki/Relation:route

**Comment by carocad** [comment]
@mehdisadeghi can you take care of this? :)

The point of this issue is to parse an OSM file and extract their public transport information from it. You can check a bit of progress that I made in [this branch](https://github.com/hiposfer/kamal/commit/0c22eae6faf3c934ef7a68fd050245c14c359c2d).

The OSM file by itself doesnt have enough information for it to be fully usable as GTFS. Nevertheless it provides, stops, routes, types of transport and providers; which is in my opinion a big first step. GTFS files are coma separated and easy to parse and write.

The idea behind this script is that the backend should not rely on OSM files containing public transport relations, so instead we will make those available through GTFS files which can be fetched separately. Furthermore, combining GTFS and OSM information on the fly can become a nightmare pretty fast.

I think this a great opportunity for your Python skills to shine! :). As this is a fire and forget operation, there is no need for this to be part of `kamal` runtime operations.

**Comment by mehdisadeghi** [comment]
Sure I'll take care of it :)

**Comment by carocad** [comment]
Check out what I just found: https://imposm.org/docs/imposm.parser/latest/

**Comment by mehdisadeghi** [comment]
@carocad it's great. Then I'll focus on extracting GTFS and not parsing OSM.

**Comment by carocad** [comment]
Oh I see. That is a shame.

Well they said that it is on "maintenance mode" so I guess it would be worth a try if you dont find a better fit ;)

**Comment by carocad** [comment]
I am closing this as the Python script already covers it: https://github.com/hiposfer/osmtogtfs/
