### ISSUE TITLE
create more protocols to generalize graph operations

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#58]
This is related to #57. @mehdisadeghi this issue should be a discussion about how to implement those and if we implement them at all. Nothing is written in stone but here is my first brain dump.

We need some more protocols to complete the behavior of a graph. This is currently not a priority because our graph is static (build at boot and never modified). However, it will become relevant as we start modifying it in real time.

Some ideas that come to mind
- protocol that a Graph should implement to handle Arc/Edge. functions:
  - `(connect graph src dst)`: creates an edge between `src` and `dst` of a graph and viceversa. Nodes should be created if non-existent?
    `(connect graph arc-or-edge)`: adds the arc or edge to the nodes incoming/outgoing edges/arcs
  - `(disconnect graph src dst)`: removes an arc from both `src` and `dst` nodes

- protocol that a Graph should implement to handle Nodes. functions:
  - `(node graph id node-attributes)`
  - ~`(node graph nodeInfo)`~ this seems contradictory as it would imply that a node *must* know its id. But currently they dont.

One thing that I intentionally left out is querying. This specially difficult in graphs and there are tons of databases and languages oriented only at solving this problem. So I think that the best way to handle is not to handle it :laughing:. 

Although that sounds stupid and contradictory, let me explain it through. Instead of trying to come up with something like `get-edges`, `get-nodes` and similar functions which just scratch the surface of the problem. I propose that we have a simple `(query graph parameters)` function/protocol which lets the graph handle how to deal with the query.

For example:
- give me all edges `(query graph [:graph/edges])`
- give me all nodes and edges `(query graph [:graph/nodes :graph/edges])`
- give me all edges from this node id `(query graph {:graph/edges {:edge/src 5}})` 

Those are just examples and are not meant to be the "standard". Most likely there will be several standards as long as people start using them. I think that is OK as this is precisely meant to be flexible not dogmatic.

References on querying:
- https://neo4j.com/docs/developer-manual/current/cypher/introduction/query-the-graph/
- http://graphql.org/learn/queries/
- https://anmonteiro.com/2016/01/om-next-query-syntax/
- http://docs.datomic.com/pull.html

**Comment by mehdisadeghi** [comment]
Thanks @carocad for you thorough explanation and the PR. I'll look at the docs for query and protocols.
