### ISSUE TITLE
optimize priority heap in Dijkstra implementation

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#76]
Currently we use the Java's default PriorityQueue which, although quite fast, is the bottleneck of the Dijkstra algorithm.

There are several priority queue implementations based on different techniques. A known alternative are fibonacci heaps. There is a mutable [Java implementation](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/util/FibonacciHeap.java) and an immutable Clojure implementation but according to its author it seems to be [quite slow](https://github.com/maryrosecook/dijkstra) ([blog post](https://maryrosecook.com/blog/post/the-fibonacci-heap-ruins-my-life)). 

Both of these algorithms are theoretically sound but according to [this blog post](http://queue.acm.org/detail.cfm?id=1814327) it seems that they are not that good in practice. The author proposes a [B-heap](https://www.wikiwand.com/en/B-heap) as a solution.

[This](https://github.com/varnish/Varnish-Cache/blob/master/lib/libvarnish/binary_heap.c) C implementation might serve as blueprint for a Java one. Although I am not sure of the applicability of this technique to Java since it is a memory-managed language

extra readings:
- [priority queue](https://www.wikiwand.com/en/Priority_queue)
- [benchmark of different Fibonacci and binary heaps](https://gabormakrai.wordpress.com/2015/02/11/experimenting-with-dijkstras-algorithm/)
- [cache oblivious structures](https://blogs.msdn.microsoft.com/devdev/2007/06/12/cache-oblivious-data-structures/) with shortest path, and priority queue recommendations
- [cache oblivious structures paper](https://pdfs.semanticscholar.org/01f8/dc5bcb94b52a92237de3f8c527d8f5c60c6f.pdf)

TODO:
- [x] measure and publish the current CPU profiling of a Dijkstra execution
- [x] test and benchmark priority queues implementation (in the context of Dijkstra executions !!)
- ~[ ] test and benchmark using an [AVL set](https://github.com/clojure/data.avl/) as a priority queue~

**Comment by carocad** [comment]
@mehdisadeghi here are two performance profiles of kamal `Dijkstra` implementation. Our current one (from #75 ) and an optimized one (from fibonacci branch). 

As you can see we spend most of our time computing the haversine, which is a complicated mathematical function that uses `asin`, which is apparently very slow. The fibonacci branch performs better because it uses another type of priority queue which is faster and becuase it avoids calling haversine on some cases.

[dijkstra-fibonacci-branch.pdf](https://github.com/hiposfer/kamal/files/1366904/dijkstra-fibonacci-branch.pdf)
[dijkstra-nearest-neighbour-branch.pdf](https://github.com/hiposfer/kamal/files/1366903/dijkstra-nearest-neighbour-branch.pdf)

**Comment by mehdisadeghi** [comment]
@carocad thanks for adding references. I'll read them.

**Comment by carocad** [comment]
PS: after thinkering the whole day with the Profiler, I am not sure anymore if `Math.asin` is a bottleneck or not. 

I tried using another library which claims to haver better math performance, yet I get mixed results:
- the leiningen benchmark says that the performance is the same with and without the library
- the JVM profiler says that it is faster with the library

I am starting to suspect that this is one of those cases where measuring something, changes its value :( 

We are getting into quantum physics here XD

![dijkstra-nearest](https://user-images.githubusercontent.com/10408729/31319474-349c9e5a-ac64-11e7-8dbe-aeecf2256716.png)
![dijkstra-jafama](https://user-images.githubusercontent.com/10408729/31319475-34d789de-ac64-11e7-9e47-8e1be2f379fb.png)
