### ISSUE TITLE
heroku deployment fails

### ISSUE THREAD

**Issue by carocad** [hiposfer/kamal#94]
I dont know why it is happening and I cannot see anything relevant on the logs :(

I thought maybe you could check this out :D ?

**Comment by carocad** [comment]
EDIT: the latest push did successfully deployed ... no idea. Please close this if you dont find any issue ;)

**Comment by mehdisadeghi** [comment]
@carocad I have already checked, it returns error code 99 which means Heroku has some errors. Meanwhile, they have probably fixed that. [Here](https://status.heroku.com) you can check Heroku status. So nothing wrong on our part  :)
